### PR TITLE
New function bubbleplot()

### PR DESCRIPTION
**Pull request by arni-magnusson**
Hi Tal,

Thanks for maintaining gplots, much appreciated. This pull request combines three commits:

1. I ran R CMD check and noticed four NOTEs related to Rd files (also listed on CRAN package webpage), fixed in 8a2b173.

2. Then I noticed that R CMD check --as-cran identifies invalid URLs in the README.md file, fixed in a6c4bfa.

3. Last, but not least, I would like to propose a basic bubbleplot() function that supports both bubbleplot(x, y, z) and bubbleplot(z~x+y), see 04427f5. It comes with example datasets catch.d and catch.r.

I was working with Greg adding the bubbleplot() function to gplots in February 2020, right at the same time as you submitted to CRAN :) Greg had reviewed the code (https://github.com/r-gregmisc/gplots/commit/e8b85d9) leading to improvements that are incorporated in the current pull request.

All documented and tested, ready for CRAN, as far as I can tell.

Cheers,
Arni

### CODE REVIEW

**Comment by talgalili** [comment]
Hi @arni-magnusson Sorry for taking this time to review!
Could you please rebase your code, and verify that there are no more issues?
If it's fine, I'll be happy to merge.

Cheers,
T

**Comment by arni-magnusson** [comment]
Hi @talgalili, thank you for following up on this. On the arni-magnusson/gplots, I've created five branches:
1. [is-r](https://github.com/arni-magnusson/gplots/tree/is-r) fixes a package warning related to deprecated use of is.R()
2. [backslash](https://github.com/arni-magnusson/gplots/tree/backslash) fixes a package warning related to backslashes in man files
3. [readme](https://github.com/arni-magnusson/gplots/tree/readme) fixes an --as-cran package warning about invalid URLs in README.md
4. [bubbleplot](https://github.com/arni-magnusson/gplots/tree/bubbleplot) adds bubbleplot() and two example datasets
5. [master](https://github.com/arni-magnusson/gplots/tree/master) combines the above commits.

**Comment by talgalili** [comment]
Dear @arni-magnusson - thank you for all the work!
I've now merged your PR, and invited you to collaborate directly to this repo.
I'll check if this version can go on CRAN or if it needs further fixes.

Cheers,
T

**Comment by arni-magnusson** [comment]
Thanks @talgalili, happy to accept the invitation. Let me know if I can help with the CRAN release.

**Comment by talgalili** [comment]
Thanks @arni-magnusson !
We'll need to fix this:
https://github.com/talgalili/gplots/issues/21
For a CRAN release.
If you'll get to it, this would help.

Thanks upfront :)

**Pull request merged**
