### PR TITLE
New function adjust_hsv()

### PR DESCRIPTION
**Pull request by arni-magnusson**
Hi Tal. I wasn't expecting to propose new functions for `gplots`, but today I was looking for a simple tool to adjust colors based on HSV values. After spending some time looking for one, I ended up writing a basic function `adjust.hsv()`.

My use case is that I had a certain blue color from a published report and wanted to create three variations of this color that are similar but different. There are probably different approaches to go about this, but my approach was to adjust the HSV values slightly to achieve nice-looking colors that are clearly related and yet different enough to distinguish between them.

Do you think this might be a useful addition to `gplots`? Or mostly harmless?

### CODE REVIEW

**Comment by talgalili** [comment]
Hi Arni,
Sounds good.
1. Could you please adjust it to be
adjust_hsv?
2. Could you please add tests?

**Comment by talgalili** [comment]
@arni-magnusson 
Could you please add unittests so that the codecoverage wouldn't decrease?

image

**Comment by talgalili** [comment]
Thanks @arni-magnusson 
Merged.

**Comment by arni-magnusson** [comment]
Splendid, thank you

**Pull request merged**
